# Generated by Django 5.1.2 on 2024-12-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fund_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fund_full_name', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('statement_of_nav', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investments', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('listed_securities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('registered_equities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ipo_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('government_bonds', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('corporate_debentures', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_government_securities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('bank_fixed_deposits', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_investments', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('bank_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_current_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_asset_value_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fund_management_and_depository_fee1', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fund_supervisor_fee1', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_asset_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('units_outstanding', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('nav_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('income_statement', models.TextField(blank=True, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('realised_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unrealised_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('preoperating_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('notice_publication_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('audit_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fund_management_and_depositary_fee2', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fund_supervisor_fee2', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
